### ISSUE TITLE
Doesn't work with recent version of pytorch-crf

### ISSUE THREAD

**Issue by claell** [deeppavlov/DeepPavlov#1599]
Want to contribute to DeepPavlov? Please read the [contributing guideline](http://docs.deeppavlov.ai/en/master/devguides/contribution_guide.html) first.

Please enter all the information below, otherwise your issue may be closed without a warning. 

**DeepPavlov version** (you can look it up by running `pip show deeppavlov`): 1.0.0

**Python version**: 3.9.5

**Operating system** (ubuntu linux, windows, ...): Windows 11

**Issue**: Error when trying a modified example from the readme.

**Content or a name of a configuration file**:
See below

**Command that led to error**:
```
model = build_model(deeppavlov.configs.ner.ner_collection3_bert, download=True)
```

**Error (including full traceback)**:
```
2022-11-10 18:35:28.686 INFO in 'deeppavlov.download'['download'] at line 138: Skipped http://files.deeppavlov.ai/v1/ner/ner_rus_bert_coll3_torch.tar.gz download because of matching hashes
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Ellsel\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Ellsel\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package perluniprops to
[nltk_data]     C:\Users\Ellsel\AppData\Roaming\nltk_data...
[nltk_data]   Package perluniprops is already up-to-date!
[nltk_data] Downloading package nonbreaking_prefixes to
[nltk_data]     C:\Users\Ellsel\AppData\Roaming\nltk_data...
[nltk_data]   Package nonbreaking_prefixes is already up-to-date!
2022-11-10 18:35:31.569 INFO in 'deeppavlov.core.data.simple_vocab'['simple_vocab'] at line 112: [loading vocabulary from C:\Users\Ellsel\.deeppavlov\models\ner_rus_bert_coll3_torch\tag.dict]
Traceback (most recent call last):
  File "c:\Users\Ellsel\Desktop\Automation\conversation.py", line 4, in <module>
    model = build_model(deeppavlov.configs.ner.ner_collection3_bert, download=True)
  File "C:\Users\Ellsel\AppData\Local\Programs\Python\Python39\lib\site-packages\deeppavlov\core\commands\infer.py", line 53, in build_model
    component = from_params(component_config, mode=mode)
  File "C:\Users\Ellsel\AppData\Local\Programs\Python\Python39\lib\site-packages\deeppavlov\core\common\params.py", line 92, in from_params
    obj = get_model(cls_name)
  File "C:\Users\Ellsel\AppData\Local\Programs\Python\Python39\lib\site-packages\deeppavlov\core\common\registry.py", line 74, in get_model
    return cls_from_str(_REGISTRY[name])
  File "C:\Users\Ellsel\AppData\Local\Programs\Python\Python39\lib\site-packages\deeppavlov\core\common\registry.py", line 42, in cls_from_str
    return getattr(importlib.import_module(module_name), cls_name)
  File "C:\Users\Ellsel\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\Ellsel\AppData\Local\Programs\Python\Python39\lib\site-packages\deeppavlov\models\torch_bert\torch_transformers_sequence_tagger.py", line 28, in <module>
    from deeppavlov.models.torch_bert.crf import CRF
  File "C:\Users\Ellsel\AppData\Local\Programs\Python\Python39\lib\site-packages\deeppavlov\models\torch_bert\crf.py", line 4, in <module>
    from torchcrf import CRF as CRFbase
ModuleNotFoundError: No module named 'torchcrf'
```

`pip install pytorch-crf==0.4.0` needed.

**Comment by IgnatovFedor** [comment]
Hi, @claell 

Before using the model from python, you still need to install all dependencies first, as described in the **Command line interface (CLI)** section in the readme. We will try to correct the readme to make this point more explicit.
To fix error, run
```bash
python -m deeppavlov install ner_collection3_bert
```
from CLI before running your python code.

**Comment by claell** [comment]
Ah, alright. Thanks for letting me know.

When I go to the section of the README, it doesn't really state this, either, though: https://github.com/deeppavlov/DeepPavlov#command-line-interface-cli

**Comment by claell** [comment]
Sorry @IgnatovFedor, maybe I overlooked it. But where has this been fixed? The README wasn't updated, at least.
