### ISSUE TITLE
Can't  install model (deeppavlov colab example )

### ISSUE THREAD

**Issue by jj449** [deeppavlov/DeepPavlov#1634]
official colab ? https://colab.research.google.com/github/deepmipt/dp_notebooks/blob/master/DP_autoFAQ.ipynb#scrollTo=UydjsTwLfryF

**DeepPavlov version** (you can look it up by running `pip show deeppavlov`):
latest ? 
**Python version**:
3.9
**Operating system** (ubuntu linux, windows, ...)colab
**Issue**:

install model error 
**Content or a name of a configuration file**:
```
tfidf_logreg_en_faq
```

**Command that led to error**:
```
!python -m deeppavlov install tfidf_logreg_en_faq
```

**Error (including full traceback)**:
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/dist-packages/deeppavlov/__main__.py", line 4, in <module>
    main()
  File "/usr/local/lib/python3.9/dist-packages/deeppavlov/deep.py", line 72, in main
    install_from_config(pipeline_config_path)
  File "/usr/local/lib/python3.9/dist-packages/deeppavlov/utils/pip_wrapper/pip_wrapper.py", line 56, in install_from_config
    requirements_files = get_config_requirements(config)
  File "/usr/local/lib/python3.9/dist-packages/deeppavlov/utils/pip_wrapper/pip_wrapper.py", line 43, in get_config_requirements
    config = parse_config(config)
  File "/usr/local/lib/python3.9/dist-packages/deeppavlov/core/commands/utils.py", line 121, in parse_config
    config = read_json(find_config(config))
  File "/usr/local/lib/python3.9/dist-packages/deeppavlov/core/common/file.py", line 53, in read_json
    with open(fpath, encoding='utf8') as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'tfidf_logreg_en_faq'
```

![image](https://user-images.githubusercontent.com/58848201/229110254-54934467-eb7a-445c-8dc6-6b81ac631b29.png)

**Comment by namanmistry** [comment]
Hey, I cannot see `config` file named `tfidf_logreg_en_faq` in `deeppavlov/configs/` section. Can you please check the name of the model that you are using?

**Comment by vaskonov** [comment]
Hey @jj449 Thank you for your interest! This colab is deprecated. I encourage you to use either [fasttext_logreg](https://github.com/deeppavlov/DeepPavlov/blob/master/deeppavlov/configs/faq/fasttext_logreg.json) as a fasttext-based solution or [topics_distilbert_base_uncased](https://github.com/deeppavlov/DeepPavlov/blob/master/deeppavlov/configs/classifiers/topics_distilbert_base_uncased.json) as a BERT-based solution.
